# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://gitlab.dkrz.de/icon/ci-tooling/codee-precommit
    rev: v2025.4.5
    hooks:
    - id: codee-format-safe
      exclude: 'mocsy'
      args: [--on-error, skip, --extensions, "f90,F90,inc,incf"]
      types: [file]

-   repo: https://github.com/PlasmaFAIR/fortitude-pre-commit
    # Fortitude version.
    rev: v0.8.0
    hooks:
      - id: fortitude
        exclude: ^(mocsy/|fabm/)
        args: [--target-std, "f2008", --line-length, "101"]

      # This is necessary here because FABM has a factory interface definition which does not
      # define an implicit intent for a parameter. Since Fortitude complains about that and we
      # have to adhere to FABM's interface, we need to ignore that specific error for the FABM
      # folder. This should be noted to FABM developers.
      - id: fortitude
        name: fortitude for fabm folder
        files: fabm
        args: [--target-std, "f2008", --line-length, "101", --ignore, C061, --ignore, E001]
